dist: xenial

language: go
go: "1.14.x"
go_import_path: /skaffold

git:
  submodules: false

branches:
  only:
    - master

jobs:
  include:
    - os: linux
      name: "checks"
      env:
        - STATICCHECK_CACHE=$HOME/linting
      script:
        - make checks
      cache:
        directories:
          - $STATICCHECK_CACHE
          - $HOME/.cache/go-build
    - os: linux
      name: "Linux unit"
      script:
        - make coverage
      cache:
        directories:
          - $HOME/.cache/go-build
    - os: osx
      name: "OSX unit"
      before_install:
        - curl -Lo ${HOME}/bin/jq https://github.com/stedolan/jq/releases/download/jq-1.5rc2/jq-osx-x86_64
        - chmod +x ${HOME}/bin/jq
      script:
        - make quicktest
      cache:
        directories:
          - $HOME/.cache/go-build
    - os: windows
      name: "Windows unit"
      script:
        - go test -short -timeout 60s ./...
      cache:
        directories:
          - C:\\Users\\travis\\AppData\\Local\\go-build
    - os: linux
      name: "integration"
      language: minimal
      script:
        - make integration-in-kind
      cache:
        directories:
          - $HOME/.cache/go-build
          - $HOME/.gradle
          - $HOME/.m2
    - os: linux
      name: "diag/Linux unit"
      script:
        - make -f Makefile.diag coverage
      cache:
        directories:
          - $HOME/.cache/go-build
    - os: osx
      name: "diag/OSX unit"
      before_install:
        - curl -Lo ${HOME}/bin/jq https://github.com/stedolan/jq/releases/download/jq-1.5rc2/jq-osx-x86_64
        - chmod +x ${HOME}/bin/jq
      script:
        - make -f Makefile.diag test
      cache:
        directories:
          - $HOME/.cache/go-build
