apiVersion: skaffold/v2beta3
kind: Config
build:
  artifacts:
  - image: skaffold-example
  tagPolicy:
    envTemplate:
      template: "{{.IMAGE_NAME}}:{{.FOO}}"
deploy:
  kubectl:
    manifests:
      - k8s-*
