apiVersion: skaffold/v2beta2
kind: Config
build:
  artifacts:
  - image: skaffold-jib-gradle
    jib: {}

# optional profile to run the jib build on Google Cloud Build
profiles:
  - name: gcb
    build:
      googleCloudBuild: {}
