apiVersion: skaffold/v2beta1
kind: Config
build:
  artifacts:
  - image: skaffold-buildpacks
    buildpack:
      builder: "heroku/buildpacks"
      env:
      - GOVERSION=1.13.1
      - GOPROXY={{.GOPROXY}}
profiles:
- name: gcb
  build:
    googleCloudBuild: {}
